apiVersion: v2
name: netbox
version: 4.9.0
appVersion: v3.4.4
description: IP address management (IPAM) and data center infrastructure management (DCIM) tool
home: https://github.com/CyberlinkAG/public-helm-charts/tree/master/charts/netbox
icon: https://raw.githubusercontent.com/netbox-community/netbox/develop/docs/netbox_logo.png
maintainers:
- name: Jan Leuenberger
  email: leuenberger@cyberlink.ch
  url: https://github.com/cyberlinkag
dependencies:
- name: postgresql
  version: 12.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: 17.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
